INSERT INTO subjects (id, label, category, description, is_published, coming_soon) VALUES ('reading', 'Reading', 'core', '', false, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, label, category, description, is_published, coming_soon) VALUES ('math', 'Maths', 'core', '', false, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, label, category, description, is_published, coming_soon) VALUES ('writing', 'Writing', 'core', '', false, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, label, category, description, is_published, coming_soon) VALUES ('critical', 'Critical Thinking', 'core', '', false, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, label, category, description, is_published, coming_soon) VALUES ('speaking', 'Speaking', 'core', '', false, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, label, category, description, is_published, coming_soon) VALUES ('biology', 'Biology', 'essential', '', false, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, label, category, description, is_published, coming_soon) VALUES ('chemistry', 'Chemistry', 'essential', '', false, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, label, category, description, is_published, coming_soon) VALUES ('physics', 'Physics', 'essential', '', false, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, label, category, description, is_published, coming_soon) VALUES ('world_history', 'World History', 'essential', '', false, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, label, category, description, is_published, coming_soon) VALUES ('nat_history', 'National History', 'essential', '', false, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, label, category, description, is_published, coming_soon) VALUES ('geography', 'Geography', 'essential', '', false, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, label, category, description, is_published, coming_soon) VALUES ('civics', 'Civics', 'essential', '', false, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, label, category, description, is_published, coming_soon) VALUES ('economics', 'Economics', 'essential', '', false, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, label, category, description, is_published, coming_soon) VALUES ('language', 'Foreign Language', 'essential', '', false, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, label, category, description, is_published, coming_soon) VALUES ('health', 'Health', 'practical', '', false, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, label, category, description, is_published, coming_soon) VALUES ('pe', 'Phys. Ed', 'practical', '', false, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, label, category, description, is_published, coming_soon) VALUES ('cooking', 'Cooking', 'practical', '', false, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, label, category, description, is_published, coming_soon) VALUES ('firstaid', 'First Aid', 'practical', '', false, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, label, category, description, is_published, coming_soon) VALUES ('digital', 'Digital Literacy', 'practical', '', false, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, label, category, description, is_published, coming_soon) VALUES ('coding', 'Coding', 'practical', '', false, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, label, category, description, is_published, coming_soon) VALUES ('literature', 'Literature', 'humanities', '', false, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, label, category, description, is_published, coming_soon) VALUES ('philosophy', 'Philosophy', 'humanities', '', false, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, label, category, description, is_published, coming_soon) VALUES ('religion', 'World Religions', 'humanities', '', false, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, label, category, description, is_published, coming_soon) VALUES ('art_history', 'Art History', 'humanities', '', false, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, label, category, description, is_published, coming_soon) VALUES ('visual_art', 'Visual Art', 'humanities', '', false, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, label, category, description, is_published, coming_soon) VALUES ('music', 'Music', 'humanities', '', false, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, label, category, description, is_published, coming_soon) VALUES ('drama', 'Drama', 'humanities', '', false, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, label, category, description, is_published, coming_soon) VALUES ('environ', 'Env. Science', 'stem', '', false, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, label, category, description, is_published, coming_soon) VALUES ('astronomy', 'Astronomy', 'stem', '', false, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, label, category, description, is_published, coming_soon) VALUES ('statistics', 'Statistics', 'stem', '', false, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, label, category, description, is_published, coming_soon) VALUES ('logic', 'Formal Logic', 'stem', '', false, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, label, category, description, is_published, coming_soon) VALUES ('engineering', 'Engineering', 'stem', '', false, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, label, category, description, is_published, coming_soon) VALUES ('psychology', 'Psychology', 'social', '', false, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, label, category, description, is_published, coming_soon) VALUES ('sociology', 'Sociology', 'social', '', false, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, label, category, description, is_published, coming_soon) VALUES ('emotional', 'Emotional Intel.', 'social', '', false, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, label, category, description, is_published, coming_soon) VALUES ('conflict', 'Conflict Res.', 'social', '', false, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, label, category, description, is_published, coming_soon) VALUES ('relationships', 'Relationships', 'social', '', false, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, label, category, description, is_published, coming_soon) VALUES ('law', 'Law', 'specialized', '', false, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, label, category, description, is_published, coming_soon) VALUES ('media', 'Media Literacy', 'specialized', '', false, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, label, category, description, is_published, coming_soon) VALUES ('research', 'Research Methods', 'specialized', '', false, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, label, category, description, is_published, coming_soon) VALUES ('entrepreneur', 'Entrepreneurship', 'specialized', '', false, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, label, category, description, is_published, coming_soon) VALUES ('architecture', 'Architecture', 'specialized', '', false, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, label, category, description, is_published, coming_soon) VALUES ('gardening', 'Gardening', 'specialized', '', false, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, label, category, description, is_published, coming_soon) VALUES ('woodwork', 'Woodworking', 'specialized', '', false, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, label, category, description, is_published, coming_soon) VALUES ('sewing', 'Sewing', 'specialized', '', false, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, label, category, description, is_published, coming_soon) VALUES ('mythology', 'Mythology', 'enrichment', '', false, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, label, category, description, is_published, coming_soon) VALUES ('chess', 'Chess', 'enrichment', '', false, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, label, category, description, is_published, coming_soon) VALUES ('dance', 'Dance', 'enrichment', '', false, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, label, category, description, is_published, coming_soon) VALUES ('film', 'Film Studies', 'enrichment', '', false, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO connections (subject_a, subject_b, description) VALUES ('reading', 'writing', 'Core Literacy — teach decoding & encoding together daily');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('reading', 'literature', 'Read great books aloud; discuss story, theme, character');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('reading', 'world_history', 'Use primary sources & historical fiction as reading material');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('reading', 'critical', 'Comprehension = evaluate what you read');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('reading', 'media', 'Analysing articles builds both skills simultaneously');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('writing', 'literature', 'Essays about books teach both craft and analysis');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('writing', 'world_history', 'Historical essays, timelines, source analysis');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('writing', 'speaking', 'Draft → speak; speech → revise into writing');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('writing', 'philosophy', 'Philosophical essays sharpen argument structure');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('writing', 'research', 'Research projects require formal written output');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('math', 'physics', 'Physics IS applied maths — vectors, forces, calculus');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('math', 'chemistry', 'Stoichiometry, molar ratios — pure applied maths');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('math', 'statistics', 'Statistics is a branch of maths');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('math', 'economics', 'Supply/demand curves, budgets, interest rates');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('math', 'logic', 'Formal logic shares mathematical proof structure');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('math', 'coding', 'Programming is applied logic and maths');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('math', 'engineering', 'Engineering design relies on maths throughout');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('math', 'architecture', 'Geometry, scale, structural load = maths');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('math', 'cooking', 'Fractions, ratios, weight, temperature');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('critical', 'philosophy', 'Philosophy is formalised critical thinking');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('critical', 'media', 'Media literacy demands critical evaluation');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('critical', 'law', 'Legal reasoning is structured critical thinking');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('critical', 'logic', 'Logic is the grammar of critical thinking');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('critical', 'research', 'Research methods train systematic critical thought');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('critical', 'chess', 'Chess builds forward planning & critical analysis');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('critical', 'economics', 'Evaluating economic arguments requires critical thought');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('speaking', 'drama', 'Drama is speaking made physical & emotional');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('speaking', 'language', 'Oral practice of a foreign language');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('speaking', 'conflict', 'Conflict resolution relies on clear communication');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('speaking', 'relationships', 'Healthy relationships need good communication');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('speaking', 'emotional', 'Expressing emotions verbally');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('biology', 'chemistry', 'Biochemistry — cell chemistry, metabolism');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('biology', 'health', 'Body systems, nutrition, disease');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('biology', 'environ', 'Ecosystems, species, conservation');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('biology', 'gardening', 'Plant biology, soil science');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('chemistry', 'physics', 'Thermodynamics, atomic structure');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('chemistry', 'cooking', 'Cooking is applied chemistry — reactions, emulsions');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('physics', 'engineering', 'Engineering applies physics principles');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('physics', 'astronomy', 'Astrophysics, gravity, electromagnetic spectrum');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('physics', 'math', 'See Math↔Physics above');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('world_history', 'nat_history', 'National story fits inside world events');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('world_history', 'geography', 'History is shaped by geography');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('world_history', 'religion', 'Religious movements shaped history deeply');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('world_history', 'art_history', 'Art reflects the era in which it was made');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('world_history', 'literature', 'Historical novels, epics from each era');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('world_history', 'philosophy', 'Philosophical movements mirror historical moments');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('world_history', 'economics', 'Economic systems drove empires and wars');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('nat_history', 'civics', 'National history is the foundation of civics');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('world_history', 'mythology', 'Myth is the oldest form of recorded history');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('geography', 'environ', 'Physical geography = environmental science');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('geography', 'civics', 'Borders, nations, political geography');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('geography', 'sociology', 'Culture is partly shaped by place');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('civics', 'law', 'Laws are the machinery of government');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('civics', 'economics', 'Policy decisions are economic decisions');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('civics', 'media', 'Understanding propaganda, bias in news');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('economics', 'entrepreneur', 'Business basics ground economic theory');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('economics', 'math', 'See Math↔Economics');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('economics', 'statistics', 'Economic analysis is statistics-heavy');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('language', 'literature', 'Read literature in the original language');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('language', 'world_history', 'Language reveals cultural history');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('language', 'mythology', 'Myths exist in every language');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('health', 'pe', 'Physical fitness is health in action');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('health', 'biology', 'Body systems, nutrition science');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('health', 'cooking', 'Nutrition and healthy meal planning');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('health', 'psychology', 'Mental health is part of whole health');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('health', 'firstaid', 'First aid is emergency health care');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('pe', 'dance', 'Dance is joyful, structured physical education');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('cooking', 'chemistry', 'See Chemistry↔Cooking');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('cooking', 'math', 'Ratios, measurement, scaling recipes');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('cooking', 'gardening', 'Grow what you cook');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('digital', 'coding', 'Digital literacy leads naturally into coding');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('digital', 'media', 'Online safety and evaluating digital sources');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('coding', 'math', 'See Math↔Coding');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('coding', 'logic', 'See Logic↔Coding');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('coding', 'engineering', 'Software is a form of engineering');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('woodwork', 'engineering', 'Design, measure, build — same process');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('woodwork', 'math', 'Measurement, angles, geometry');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('sewing', 'math', 'Patterns use geometry and measurement');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('sewing', 'art_history', 'Fashion as art through history');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('gardening', 'biology', 'See Biology↔Gardening');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('gardening', 'environ', 'Sustainability, soil, ecosystems');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('architecture', 'visual_art', 'Design sense is shared across both');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('architecture', 'engineering', 'Structural integrity = applied engineering');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('architecture', 'math', 'See Math↔Architecture');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('literature', 'philosophy', 'Great novels explore philosophical questions');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('literature', 'world_history', 'Literature reflects its historical moment');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('literature', 'mythology', 'Myths are the oldest literature');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('literature', 'film', 'Film adapts literature; same narrative tools');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('philosophy', 'religion', 'Philosophy of religion, moral theology');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('philosophy', 'critical', 'See Critical↔Philosophy');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('philosophy', 'psychology', 'Philosophy of mind, consciousness');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('religion', 'world_history', 'See Religion↔History');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('religion', 'sociology', 'Belief systems shape social structures');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('religion', 'mythology', 'Mythology often IS religious narrative');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('art_history', 'visual_art', 'Art history contextualises art-making');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('art_history', 'world_history', 'See Art History↔World History');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('visual_art', 'architecture', 'Spatial design, aesthetics');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('visual_art', 'film', 'Cinematography is visual art in motion');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('music', 'math', 'Time signatures, ratios, harmony theory');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('music', 'physics', 'Acoustics — sound waves, resonance');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('music', 'world_history', 'Music is a record of its time');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('music', 'dance', 'Rhythm, movement, expression together');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('drama', 'literature', 'Plays ARE literature; perform what you read');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('drama', 'emotional', 'Acting demands emotional intelligence');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('drama', 'speaking', 'See Speaking↔Drama');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('environ', 'geography', 'See Geography↔Environ');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('environ', 'biology', 'See Biology↔Environ');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('astronomy', 'physics', 'See Physics↔Astronomy');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('astronomy', 'math', 'Scale, distance, orbital mechanics');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('astronomy', 'mythology', 'Constellations are named by myth');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('statistics', 'math', 'See Math↔Statistics');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('statistics', 'research', 'Research requires statistical analysis');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('statistics', 'economics', 'See Economics↔Statistics');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('logic', 'coding', 'See Coding↔Logic');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('logic', 'philosophy', 'Formal logic is used in philosophical argument');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('logic', 'chess', 'Chess is applied logic and strategy');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('engineering', 'math', 'See Math↔Engineering');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('engineering', 'physics', 'See Physics↔Engineering');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('psychology', 'sociology', 'Individual behaviour vs group behaviour');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('psychology', 'health', 'Mental health');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('psychology', 'emotional', 'Emotional intelligence is applied psychology');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('psychology', 'relationships', 'Understanding self helps understand others');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('psychology', 'drama', 'Acting requires understanding human psychology');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('sociology', 'world_history', 'History is shaped by social forces');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('sociology', 'civics', 'How societies organise politically');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('emotional', 'conflict', 'Emotional awareness enables conflict resolution');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('emotional', 'relationships', 'EQ is the foundation of healthy relationships');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('conflict', 'law', 'Formal dispute resolution is structured conflict res.');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('conflict', 'speaking', 'See Speaking↔Conflict');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('law', 'civics', 'See Civics↔Law');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('law', 'critical', 'See Critical↔Law');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('law', 'writing', 'Legal writing is a discipline in itself');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('media', 'digital', 'See Digital↔Media');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('media', 'critical', 'See Critical↔Media');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('research', 'writing', 'See Writing↔Research');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('research', 'statistics', 'See Statistics↔Research');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('entrepreneur', 'economics', 'See Economics↔Entrepreneur');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('entrepreneur', 'math', 'Business maths: profit, loss, interest');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('mythology', 'literature', 'See Literature↔Mythology');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('mythology', 'world_history', 'See Mythology↔History');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('mythology', 'religion', 'See Religion↔Mythology');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('chess', 'critical', 'See Critical↔Chess');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('chess', 'math', 'Chess scoring, probability, combinatorics');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('chess', 'logic', 'See Logic↔Chess');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('dance', 'pe', 'See PE↔Dance');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('dance', 'music', 'See Music↔Dance');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('dance', 'drama', 'Expressive performance overlap');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('film', 'literature', 'See Film↔Literature');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('film', 'art_history', 'Cinema as 20th-century art form');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('film', 'world_history', 'Film as historical document and propaganda');
INSERT INTO connections (subject_a, subject_b, description) VALUES ('film', 'media', 'Media literacy applied to moving image');
